### ISSUE TITLE
[BUG] - version 0.6 not compatible

### ISSUE THREAD

**Issue by tramhao** [veeso/tui-realm-treeview#5]
Would you please upgrade this component to make it compatible with version 0.6 of tuirealm? Thanks so much

**Comment by veeso** [comment]
I can't. Since this component is a wrapper around library <https://crates.io/crates/tui-tree-widget> and its author hasn't released yet an update to make it compatible with tui 0.16, I cannot update this to work with tui-realm 0.6.0.

Unfortunately tui 0.16 requires crossterm 0.20, which is not compatible with crossterm 0.19, so the author must upgrade the library dependencies.

If I can find the time, I will open a PR on that repo to bump tui.

In the meanwhile you can keep using tui-realm 0.5.0, which is perfectly fine, you just can't align titles.

**Comment by tramhao** [comment]
Thanks and I'll keep using 0.5. Have a nice day.

**Comment by EdJoPaTo** [comment]
Hello there o/

Its interesting to find out some library is using my crate. Nice :D
Thanks @tramhao to let me know my crate is used here.

[tui-tree-widget v0.7](https://github.com/EdJoPaTo/tui-rs-tree-widget/releases/tag/v0.7.0) has support for tui 0.16 which I released 3 days ago. So It should be possible to bump the version here too?

**Comment by veeso** [comment]
Whoops, github didn't notify me about that 😅 . I will release the update asap

**Comment by veeso** [comment]
version 0.3.0 released
